// Code generated by ogen, DO NOT EDIT.

package oapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAPIKey handles api_key security.
	HandleAPIKey(ctx context.Context, operationName OperationName, t APIKey) (context.Context, error)
	// HandleBearer handles bearer security.
	HandleBearer(ctx context.Context, operationName OperationName, t Bearer) (context.Context, error)
	// HandleCookie handles cookie security.
	HandleCookie(ctx context.Context, operationName OperationName, t Cookie) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesAPIKey = map[string][]string{
	AddAssetsToAlbumOperation:             []string{},
	AddMemoryAssetsOperation:              []string{},
	AddSharedLinkAssetsOperation:          []string{},
	AddUsersToAlbumOperation:              []string{},
	BulkTagAssetsOperation:                []string{},
	ChangePasswordOperation:               []string{},
	ChangePinCodeOperation:                []string{},
	CheckBulkUploadOperation:              []string{},
	CheckExistingAssetsOperation:          []string{},
	CreateActivityOperation:               []string{},
	CreateAlbumOperation:                  []string{},
	CreateApiKeyOperation:                 []string{},
	CreateFaceOperation:                   []string{},
	CreateJobOperation:                    []string{},
	CreateLibraryOperation:                []string{},
	CreateMemoryOperation:                 []string{},
	CreateNotificationOperation:           []string{},
	CreatePartnerOperation:                []string{},
	CreatePersonOperation:                 []string{},
	CreateProfileImageOperation:           []string{},
	CreateSessionOperation:                []string{},
	CreateSharedLinkOperation:             []string{},
	CreateStackOperation:                  []string{},
	CreateTagOperation:                    []string{},
	CreateUserAdminOperation:              []string{},
	DeleteActivityOperation:               []string{},
	DeleteAlbumOperation:                  []string{},
	DeleteAllSessionsOperation:            []string{},
	DeleteApiKeyOperation:                 []string{},
	DeleteAssetsOperation:                 []string{},
	DeleteFaceOperation:                   []string{},
	DeleteLibraryOperation:                []string{},
	DeleteMemoryOperation:                 []string{},
	DeleteNotificationOperation:           []string{},
	DeleteNotificationsOperation:          []string{},
	DeleteProfileImageOperation:           []string{},
	DeleteServerLicenseOperation:          []string{},
	DeleteSessionOperation:                []string{},
	DeleteStackOperation:                  []string{},
	DeleteStacksOperation:                 []string{},
	DeleteSyncAckOperation:                []string{},
	DeleteTagOperation:                    []string{},
	DeleteUserAdminOperation:              []string{},
	DeleteUserLicenseOperation:            []string{},
	DownloadArchiveOperation:              []string{},
	DownloadAssetOperation:                []string{},
	EmptyTrashOperation:                   []string{},
	GetAboutInfoOperation:                 []string{},
	GetActivitiesOperation:                []string{},
	GetActivityStatisticsOperation:        []string{},
	GetAdminOnboardingOperation:           []string{},
	GetAlbumInfoOperation:                 []string{},
	GetAlbumStatisticsOperation:           []string{},
	GetAllAlbumsOperation:                 []string{},
	GetAllJobsStatusOperation:             []string{},
	GetAllLibrariesOperation:              []string{},
	GetAllPeopleOperation:                 []string{},
	GetAllSharedLinksOperation:            []string{},
	GetAllTagsOperation:                   []string{},
	GetAllUserAssetsByDeviceIdOperation:   []string{},
	GetApiKeyOperation:                    []string{},
	GetApiKeysOperation:                   []string{},
	GetAssetDuplicatesOperation:           []string{},
	GetAssetInfoOperation:                 []string{},
	GetAssetStatisticsOperation:           []string{},
	GetAssetsByCityOperation:              []string{},
	GetAssetsByOriginalPathOperation:      []string{},
	GetAuthStatusOperation:                []string{},
	GetConfigOperation:                    []string{},
	GetConfigDefaultsOperation:            []string{},
	GetDeltaSyncOperation:                 []string{},
	GetDownloadInfoOperation:              []string{},
	GetExploreDataOperation:               []string{},
	GetFacesOperation:                     []string{},
	GetFullSyncForUserOperation:           []string{},
	GetLibraryOperation:                   []string{},
	GetLibraryStatisticsOperation:         []string{},
	GetMapMarkersOperation:                []string{},
	GetMemoryOperation:                    []string{},
	GetMyPreferencesOperation:             []string{},
	GetMySharedLinkOperation:              []string{},
	GetMyUserOperation:                    []string{},
	GetNotificationOperation:              []string{},
	GetNotificationTemplateAdminOperation: []string{},
	GetNotificationsOperation:             []string{},
	GetPartnersOperation:                  []string{},
	GetPersonOperation:                    []string{},
	GetPersonStatisticsOperation:          []string{},
	GetPersonThumbnailOperation:           []string{},
	GetProfileImageOperation:              []string{},
	GetRandomOperation:                    []string{},
	GetReverseGeocodingStateOperation:     []string{},
	GetSearchSuggestionsOperation:         []string{},
	GetServerLicenseOperation:             []string{},
	GetServerStatisticsOperation:          []string{},
	GetSessionsOperation:                  []string{},
	GetSharedLinkByIdOperation:            []string{},
	GetStackOperation:                     []string{},
	GetStorageOperation:                   []string{},
	GetStorageTemplateOptionsOperation:    []string{},
	GetSyncAckOperation:                   []string{},
	GetSyncStreamOperation:                []string{},
	GetTagByIdOperation:                   []string{},
	GetTimeBucketOperation:                []string{},
	GetTimeBucketsOperation:               []string{},
	GetUniqueOriginalPathsOperation:       []string{},
	GetUserOperation:                      []string{},
	GetUserAdminOperation:                 []string{},
	GetUserLicenseOperation:               []string{},
	GetUserPreferencesAdminOperation:      []string{},
	GetUserStatisticsAdminOperation:       []string{},
	LinkOAuthAccountOperation:             []string{},
	LockAuthSessionOperation:              []string{},
	LockSessionOperation:                  []string{},
	LogoutOperation:                       []string{},
	MergePersonOperation:                  []string{},
	PlayAssetVideoOperation:               []string{},
	ReassignFacesOperation:                []string{},
	ReassignFacesByIdOperation:            []string{},
	RemoveAssetFromAlbumOperation:         []string{},
	RemoveMemoryAssetsOperation:           []string{},
	RemovePartnerOperation:                []string{},
	RemoveSharedLinkOperation:             []string{},
	RemoveSharedLinkAssetsOperation:       []string{},
	RemoveUserFromAlbumOperation:          []string{},
	ReplaceAssetOperation:                 []string{},
	ResetPinCodeOperation:                 []string{},
	RestoreAssetsOperation:                []string{},
	RestoreTrashOperation:                 []string{},
	RestoreUserAdminOperation:             []string{},
	ReverseGeocodeOperation:               []string{},
	RunAssetJobsOperation:                 []string{},
	ScanLibraryOperation:                  []string{},
	SearchAssetsOperation:                 []string{},
	SearchMemoriesOperation:               []string{},
	SearchPersonOperation:                 []string{},
	SearchPlacesOperation:                 []string{},
	SearchRandomOperation:                 []string{},
	SearchSmartOperation:                  []string{},
	SearchStacksOperation:                 []string{},
	SearchUsersOperation:                  []string{},
	SearchUsersAdminOperation:             []string{},
	SendJobCommandOperation:               []string{},
	SendSyncAckOperation:                  []string{},
	SendTestEmailAdminOperation:           []string{},
	SetServerLicenseOperation:             []string{},
	SetUserLicenseOperation:               []string{},
	SetupPinCodeOperation:                 []string{},
	TagAssetsOperation:                    []string{},
	UnlinkOAuthAccountOperation:           []string{},
	UnlockAuthSessionOperation:            []string{},
	UntagAssetsOperation:                  []string{},
	UpdateAdminOnboardingOperation:        []string{},
	UpdateAlbumInfoOperation:              []string{},
	UpdateAlbumUserOperation:              []string{},
	UpdateApiKeyOperation:                 []string{},
	UpdateAssetOperation:                  []string{},
	UpdateAssetsOperation:                 []string{},
	UpdateConfigOperation:                 []string{},
	UpdateLibraryOperation:                []string{},
	UpdateMemoryOperation:                 []string{},
	UpdateMyPreferencesOperation:          []string{},
	UpdateMyUserOperation:                 []string{},
	UpdateNotificationOperation:           []string{},
	UpdateNotificationsOperation:          []string{},
	UpdatePartnerOperation:                []string{},
	UpdatePeopleOperation:                 []string{},
	UpdatePersonOperation:                 []string{},
	UpdateSharedLinkOperation:             []string{},
	UpdateStackOperation:                  []string{},
	UpdateTagOperation:                    []string{},
	UpdateUserAdminOperation:              []string{},
	UpdateUserPreferencesAdminOperation:   []string{},
	UploadAssetOperation:                  []string{},
	UpsertTagsOperation:                   []string{},
	ValidateOperation:                     []string{},
	ValidateAccessTokenOperation:          []string{},
	ViewAssetOperation:                    []string{},
}

func (s *Server) securityAPIKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t APIKey
	const parameterName = "x-api-key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesAPIKey[operationName]
	rctx, err := s.sec.HandleAPIKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

var operationRolesBearer = map[string][]string{
	AddAssetsToAlbumOperation:             []string{},
	AddMemoryAssetsOperation:              []string{},
	AddSharedLinkAssetsOperation:          []string{},
	AddUsersToAlbumOperation:              []string{},
	BulkTagAssetsOperation:                []string{},
	ChangePasswordOperation:               []string{},
	ChangePinCodeOperation:                []string{},
	CheckBulkUploadOperation:              []string{},
	CheckExistingAssetsOperation:          []string{},
	CreateActivityOperation:               []string{},
	CreateAlbumOperation:                  []string{},
	CreateApiKeyOperation:                 []string{},
	CreateFaceOperation:                   []string{},
	CreateJobOperation:                    []string{},
	CreateLibraryOperation:                []string{},
	CreateMemoryOperation:                 []string{},
	CreateNotificationOperation:           []string{},
	CreatePartnerOperation:                []string{},
	CreatePersonOperation:                 []string{},
	CreateProfileImageOperation:           []string{},
	CreateSessionOperation:                []string{},
	CreateSharedLinkOperation:             []string{},
	CreateStackOperation:                  []string{},
	CreateTagOperation:                    []string{},
	CreateUserAdminOperation:              []string{},
	DeleteActivityOperation:               []string{},
	DeleteAlbumOperation:                  []string{},
	DeleteAllSessionsOperation:            []string{},
	DeleteApiKeyOperation:                 []string{},
	DeleteAssetsOperation:                 []string{},
	DeleteFaceOperation:                   []string{},
	DeleteLibraryOperation:                []string{},
	DeleteMemoryOperation:                 []string{},
	DeleteNotificationOperation:           []string{},
	DeleteNotificationsOperation:          []string{},
	DeleteProfileImageOperation:           []string{},
	DeleteServerLicenseOperation:          []string{},
	DeleteSessionOperation:                []string{},
	DeleteStackOperation:                  []string{},
	DeleteStacksOperation:                 []string{},
	DeleteSyncAckOperation:                []string{},
	DeleteTagOperation:                    []string{},
	DeleteUserAdminOperation:              []string{},
	DeleteUserLicenseOperation:            []string{},
	DownloadArchiveOperation:              []string{},
	DownloadAssetOperation:                []string{},
	EmptyTrashOperation:                   []string{},
	GetAboutInfoOperation:                 []string{},
	GetActivitiesOperation:                []string{},
	GetActivityStatisticsOperation:        []string{},
	GetAdminOnboardingOperation:           []string{},
	GetAlbumInfoOperation:                 []string{},
	GetAlbumStatisticsOperation:           []string{},
	GetAllAlbumsOperation:                 []string{},
	GetAllJobsStatusOperation:             []string{},
	GetAllLibrariesOperation:              []string{},
	GetAllPeopleOperation:                 []string{},
	GetAllSharedLinksOperation:            []string{},
	GetAllTagsOperation:                   []string{},
	GetAllUserAssetsByDeviceIdOperation:   []string{},
	GetApiKeyOperation:                    []string{},
	GetApiKeysOperation:                   []string{},
	GetAssetDuplicatesOperation:           []string{},
	GetAssetInfoOperation:                 []string{},
	GetAssetStatisticsOperation:           []string{},
	GetAssetsByCityOperation:              []string{},
	GetAssetsByOriginalPathOperation:      []string{},
	GetAuthStatusOperation:                []string{},
	GetConfigOperation:                    []string{},
	GetConfigDefaultsOperation:            []string{},
	GetDeltaSyncOperation:                 []string{},
	GetDownloadInfoOperation:              []string{},
	GetExploreDataOperation:               []string{},
	GetFacesOperation:                     []string{},
	GetFullSyncForUserOperation:           []string{},
	GetLibraryOperation:                   []string{},
	GetLibraryStatisticsOperation:         []string{},
	GetMapMarkersOperation:                []string{},
	GetMemoryOperation:                    []string{},
	GetMyPreferencesOperation:             []string{},
	GetMySharedLinkOperation:              []string{},
	GetMyUserOperation:                    []string{},
	GetNotificationOperation:              []string{},
	GetNotificationTemplateAdminOperation: []string{},
	GetNotificationsOperation:             []string{},
	GetPartnersOperation:                  []string{},
	GetPersonOperation:                    []string{},
	GetPersonStatisticsOperation:          []string{},
	GetPersonThumbnailOperation:           []string{},
	GetProfileImageOperation:              []string{},
	GetRandomOperation:                    []string{},
	GetReverseGeocodingStateOperation:     []string{},
	GetSearchSuggestionsOperation:         []string{},
	GetServerLicenseOperation:             []string{},
	GetServerStatisticsOperation:          []string{},
	GetSessionsOperation:                  []string{},
	GetSharedLinkByIdOperation:            []string{},
	GetStackOperation:                     []string{},
	GetStorageOperation:                   []string{},
	GetStorageTemplateOptionsOperation:    []string{},
	GetSyncAckOperation:                   []string{},
	GetSyncStreamOperation:                []string{},
	GetTagByIdOperation:                   []string{},
	GetTimeBucketOperation:                []string{},
	GetTimeBucketsOperation:               []string{},
	GetUniqueOriginalPathsOperation:       []string{},
	GetUserOperation:                      []string{},
	GetUserAdminOperation:                 []string{},
	GetUserLicenseOperation:               []string{},
	GetUserPreferencesAdminOperation:      []string{},
	GetUserStatisticsAdminOperation:       []string{},
	LinkOAuthAccountOperation:             []string{},
	LockAuthSessionOperation:              []string{},
	LockSessionOperation:                  []string{},
	LogoutOperation:                       []string{},
	MergePersonOperation:                  []string{},
	PlayAssetVideoOperation:               []string{},
	ReassignFacesOperation:                []string{},
	ReassignFacesByIdOperation:            []string{},
	RemoveAssetFromAlbumOperation:         []string{},
	RemoveMemoryAssetsOperation:           []string{},
	RemovePartnerOperation:                []string{},
	RemoveSharedLinkOperation:             []string{},
	RemoveSharedLinkAssetsOperation:       []string{},
	RemoveUserFromAlbumOperation:          []string{},
	ReplaceAssetOperation:                 []string{},
	ResetPinCodeOperation:                 []string{},
	RestoreAssetsOperation:                []string{},
	RestoreTrashOperation:                 []string{},
	RestoreUserAdminOperation:             []string{},
	ReverseGeocodeOperation:               []string{},
	RunAssetJobsOperation:                 []string{},
	ScanLibraryOperation:                  []string{},
	SearchAssetsOperation:                 []string{},
	SearchMemoriesOperation:               []string{},
	SearchPersonOperation:                 []string{},
	SearchPlacesOperation:                 []string{},
	SearchRandomOperation:                 []string{},
	SearchSmartOperation:                  []string{},
	SearchStacksOperation:                 []string{},
	SearchUsersOperation:                  []string{},
	SearchUsersAdminOperation:             []string{},
	SendJobCommandOperation:               []string{},
	SendSyncAckOperation:                  []string{},
	SendTestEmailAdminOperation:           []string{},
	SetServerLicenseOperation:             []string{},
	SetUserLicenseOperation:               []string{},
	SetupPinCodeOperation:                 []string{},
	TagAssetsOperation:                    []string{},
	UnlinkOAuthAccountOperation:           []string{},
	UnlockAuthSessionOperation:            []string{},
	UntagAssetsOperation:                  []string{},
	UpdateAdminOnboardingOperation:        []string{},
	UpdateAlbumInfoOperation:              []string{},
	UpdateAlbumUserOperation:              []string{},
	UpdateApiKeyOperation:                 []string{},
	UpdateAssetOperation:                  []string{},
	UpdateAssetsOperation:                 []string{},
	UpdateConfigOperation:                 []string{},
	UpdateLibraryOperation:                []string{},
	UpdateMemoryOperation:                 []string{},
	UpdateMyPreferencesOperation:          []string{},
	UpdateMyUserOperation:                 []string{},
	UpdateNotificationOperation:           []string{},
	UpdateNotificationsOperation:          []string{},
	UpdatePartnerOperation:                []string{},
	UpdatePeopleOperation:                 []string{},
	UpdatePersonOperation:                 []string{},
	UpdateSharedLinkOperation:             []string{},
	UpdateStackOperation:                  []string{},
	UpdateTagOperation:                    []string{},
	UpdateUserAdminOperation:              []string{},
	UpdateUserPreferencesAdminOperation:   []string{},
	UploadAssetOperation:                  []string{},
	UpsertTagsOperation:                   []string{},
	ValidateOperation:                     []string{},
	ValidateAccessTokenOperation:          []string{},
	ViewAssetOperation:                    []string{},
}

func (s *Server) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Bearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearer[operationName]
	rctx, err := s.sec.HandleBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

var operationRolesCookie = map[string][]string{
	AddAssetsToAlbumOperation:             []string{},
	AddMemoryAssetsOperation:              []string{},
	AddSharedLinkAssetsOperation:          []string{},
	AddUsersToAlbumOperation:              []string{},
	BulkTagAssetsOperation:                []string{},
	ChangePasswordOperation:               []string{},
	ChangePinCodeOperation:                []string{},
	CheckBulkUploadOperation:              []string{},
	CheckExistingAssetsOperation:          []string{},
	CreateActivityOperation:               []string{},
	CreateAlbumOperation:                  []string{},
	CreateApiKeyOperation:                 []string{},
	CreateFaceOperation:                   []string{},
	CreateJobOperation:                    []string{},
	CreateLibraryOperation:                []string{},
	CreateMemoryOperation:                 []string{},
	CreateNotificationOperation:           []string{},
	CreatePartnerOperation:                []string{},
	CreatePersonOperation:                 []string{},
	CreateProfileImageOperation:           []string{},
	CreateSessionOperation:                []string{},
	CreateSharedLinkOperation:             []string{},
	CreateStackOperation:                  []string{},
	CreateTagOperation:                    []string{},
	CreateUserAdminOperation:              []string{},
	DeleteActivityOperation:               []string{},
	DeleteAlbumOperation:                  []string{},
	DeleteAllSessionsOperation:            []string{},
	DeleteApiKeyOperation:                 []string{},
	DeleteAssetsOperation:                 []string{},
	DeleteFaceOperation:                   []string{},
	DeleteLibraryOperation:                []string{},
	DeleteMemoryOperation:                 []string{},
	DeleteNotificationOperation:           []string{},
	DeleteNotificationsOperation:          []string{},
	DeleteProfileImageOperation:           []string{},
	DeleteServerLicenseOperation:          []string{},
	DeleteSessionOperation:                []string{},
	DeleteStackOperation:                  []string{},
	DeleteStacksOperation:                 []string{},
	DeleteSyncAckOperation:                []string{},
	DeleteTagOperation:                    []string{},
	DeleteUserAdminOperation:              []string{},
	DeleteUserLicenseOperation:            []string{},
	DownloadArchiveOperation:              []string{},
	DownloadAssetOperation:                []string{},
	EmptyTrashOperation:                   []string{},
	GetAboutInfoOperation:                 []string{},
	GetActivitiesOperation:                []string{},
	GetActivityStatisticsOperation:        []string{},
	GetAdminOnboardingOperation:           []string{},
	GetAlbumInfoOperation:                 []string{},
	GetAlbumStatisticsOperation:           []string{},
	GetAllAlbumsOperation:                 []string{},
	GetAllJobsStatusOperation:             []string{},
	GetAllLibrariesOperation:              []string{},
	GetAllPeopleOperation:                 []string{},
	GetAllSharedLinksOperation:            []string{},
	GetAllTagsOperation:                   []string{},
	GetAllUserAssetsByDeviceIdOperation:   []string{},
	GetApiKeyOperation:                    []string{},
	GetApiKeysOperation:                   []string{},
	GetAssetDuplicatesOperation:           []string{},
	GetAssetInfoOperation:                 []string{},
	GetAssetStatisticsOperation:           []string{},
	GetAssetsByCityOperation:              []string{},
	GetAssetsByOriginalPathOperation:      []string{},
	GetAuthStatusOperation:                []string{},
	GetConfigOperation:                    []string{},
	GetConfigDefaultsOperation:            []string{},
	GetDeltaSyncOperation:                 []string{},
	GetDownloadInfoOperation:              []string{},
	GetExploreDataOperation:               []string{},
	GetFacesOperation:                     []string{},
	GetFullSyncForUserOperation:           []string{},
	GetLibraryOperation:                   []string{},
	GetLibraryStatisticsOperation:         []string{},
	GetMapMarkersOperation:                []string{},
	GetMemoryOperation:                    []string{},
	GetMyPreferencesOperation:             []string{},
	GetMySharedLinkOperation:              []string{},
	GetMyUserOperation:                    []string{},
	GetNotificationOperation:              []string{},
	GetNotificationTemplateAdminOperation: []string{},
	GetNotificationsOperation:             []string{},
	GetPartnersOperation:                  []string{},
	GetPersonOperation:                    []string{},
	GetPersonStatisticsOperation:          []string{},
	GetPersonThumbnailOperation:           []string{},
	GetProfileImageOperation:              []string{},
	GetRandomOperation:                    []string{},
	GetReverseGeocodingStateOperation:     []string{},
	GetSearchSuggestionsOperation:         []string{},
	GetServerLicenseOperation:             []string{},
	GetServerStatisticsOperation:          []string{},
	GetSessionsOperation:                  []string{},
	GetSharedLinkByIdOperation:            []string{},
	GetStackOperation:                     []string{},
	GetStorageOperation:                   []string{},
	GetStorageTemplateOptionsOperation:    []string{},
	GetSyncAckOperation:                   []string{},
	GetSyncStreamOperation:                []string{},
	GetTagByIdOperation:                   []string{},
	GetTimeBucketOperation:                []string{},
	GetTimeBucketsOperation:               []string{},
	GetUniqueOriginalPathsOperation:       []string{},
	GetUserOperation:                      []string{},
	GetUserAdminOperation:                 []string{},
	GetUserLicenseOperation:               []string{},
	GetUserPreferencesAdminOperation:      []string{},
	GetUserStatisticsAdminOperation:       []string{},
	LinkOAuthAccountOperation:             []string{},
	LockAuthSessionOperation:              []string{},
	LockSessionOperation:                  []string{},
	LogoutOperation:                       []string{},
	MergePersonOperation:                  []string{},
	PlayAssetVideoOperation:               []string{},
	ReassignFacesOperation:                []string{},
	ReassignFacesByIdOperation:            []string{},
	RemoveAssetFromAlbumOperation:         []string{},
	RemoveMemoryAssetsOperation:           []string{},
	RemovePartnerOperation:                []string{},
	RemoveSharedLinkOperation:             []string{},
	RemoveSharedLinkAssetsOperation:       []string{},
	RemoveUserFromAlbumOperation:          []string{},
	ReplaceAssetOperation:                 []string{},
	ResetPinCodeOperation:                 []string{},
	RestoreAssetsOperation:                []string{},
	RestoreTrashOperation:                 []string{},
	RestoreUserAdminOperation:             []string{},
	ReverseGeocodeOperation:               []string{},
	RunAssetJobsOperation:                 []string{},
	ScanLibraryOperation:                  []string{},
	SearchAssetsOperation:                 []string{},
	SearchMemoriesOperation:               []string{},
	SearchPersonOperation:                 []string{},
	SearchPlacesOperation:                 []string{},
	SearchRandomOperation:                 []string{},
	SearchSmartOperation:                  []string{},
	SearchStacksOperation:                 []string{},
	SearchUsersOperation:                  []string{},
	SearchUsersAdminOperation:             []string{},
	SendJobCommandOperation:               []string{},
	SendSyncAckOperation:                  []string{},
	SendTestEmailAdminOperation:           []string{},
	SetServerLicenseOperation:             []string{},
	SetUserLicenseOperation:               []string{},
	SetupPinCodeOperation:                 []string{},
	TagAssetsOperation:                    []string{},
	UnlinkOAuthAccountOperation:           []string{},
	UnlockAuthSessionOperation:            []string{},
	UntagAssetsOperation:                  []string{},
	UpdateAdminOnboardingOperation:        []string{},
	UpdateAlbumInfoOperation:              []string{},
	UpdateAlbumUserOperation:              []string{},
	UpdateApiKeyOperation:                 []string{},
	UpdateAssetOperation:                  []string{},
	UpdateAssetsOperation:                 []string{},
	UpdateConfigOperation:                 []string{},
	UpdateLibraryOperation:                []string{},
	UpdateMemoryOperation:                 []string{},
	UpdateMyPreferencesOperation:          []string{},
	UpdateMyUserOperation:                 []string{},
	UpdateNotificationOperation:           []string{},
	UpdateNotificationsOperation:          []string{},
	UpdatePartnerOperation:                []string{},
	UpdatePeopleOperation:                 []string{},
	UpdatePersonOperation:                 []string{},
	UpdateSharedLinkOperation:             []string{},
	UpdateStackOperation:                  []string{},
	UpdateTagOperation:                    []string{},
	UpdateUserAdminOperation:              []string{},
	UpdateUserPreferencesAdminOperation:   []string{},
	UploadAssetOperation:                  []string{},
	UpsertTagsOperation:                   []string{},
	ValidateOperation:                     []string{},
	ValidateAccessTokenOperation:          []string{},
	ViewAssetOperation:                    []string{},
}

func (s *Server) securityCookie(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Cookie
	const parameterName = "immich_access_token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesCookie[operationName]
	rctx, err := s.sec.HandleCookie(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// APIKey provides api_key security value.
	APIKey(ctx context.Context, operationName OperationName) (APIKey, error)
	// Bearer provides bearer security value.
	Bearer(ctx context.Context, operationName OperationName) (Bearer, error)
	// Cookie provides cookie security value.
	Cookie(ctx context.Context, operationName OperationName) (Cookie, error)
}

func (s *Client) securityAPIKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.APIKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"APIKey\"")
	}
	req.Header.Set("x-api-key", t.APIKey)
	return nil
}
func (s *Client) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Bearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Bearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityCookie(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Cookie(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Cookie\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "immich_access_token",
		Value: t.APIKey,
	})
	return nil
}
