// Code generated by ogen, DO NOT EDIT.

package oapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddAssetsToAlbum implements addAssetsToAlbum operation.
//
// PUT /albums/{id}/assets
func (UnimplementedHandler) AddAssetsToAlbum(ctx context.Context, req *BulkIdsDto, params AddAssetsToAlbumParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// AddMemoryAssets implements addMemoryAssets operation.
//
// PUT /memories/{id}/assets
func (UnimplementedHandler) AddMemoryAssets(ctx context.Context, req *BulkIdsDto, params AddMemoryAssetsParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// AddSharedLinkAssets implements addSharedLinkAssets operation.
//
// PUT /shared-links/{id}/assets
func (UnimplementedHandler) AddSharedLinkAssets(ctx context.Context, req *AssetIdsDto, params AddSharedLinkAssetsParams) (r []AssetIdsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// AddUsersToAlbum implements addUsersToAlbum operation.
//
// PUT /albums/{id}/users
func (UnimplementedHandler) AddUsersToAlbum(ctx context.Context, req *AddUsersDto, params AddUsersToAlbumParams) (r *AlbumResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// BulkTagAssets implements bulkTagAssets operation.
//
// PUT /tags/assets
func (UnimplementedHandler) BulkTagAssets(ctx context.Context, req *TagBulkAssetsDto) (r *TagBulkAssetsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangePassword implements changePassword operation.
//
// POST /auth/change-password
func (UnimplementedHandler) ChangePassword(ctx context.Context, req *ChangePasswordDto) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CheckBulkUpload implements checkBulkUpload operation.
//
// Checks if assets exist by checksums.
//
// POST /assets/bulk-upload-check
func (UnimplementedHandler) CheckBulkUpload(ctx context.Context, req *AssetBulkUploadCheckDto) (r *AssetBulkUploadCheckResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CheckExistingAssets implements checkExistingAssets operation.
//
// Checks if multiple assets exist on the server and returns all existing - used by background backup.
//
// POST /assets/exist
func (UnimplementedHandler) CheckExistingAssets(ctx context.Context, req *CheckExistingAssetsDto) (r *CheckExistingAssetsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateActivity implements createActivity operation.
//
// POST /activities
func (UnimplementedHandler) CreateActivity(ctx context.Context, req *ActivityCreateDto) (r *ActivityResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAlbum implements createAlbum operation.
//
// POST /albums
func (UnimplementedHandler) CreateAlbum(ctx context.Context, req *CreateAlbumDto) (r *AlbumResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApiKey implements createApiKey operation.
//
// POST /api-keys
func (UnimplementedHandler) CreateApiKey(ctx context.Context, req *APIKeyCreateDto) (r *APIKeyCreateResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateJob implements createJob operation.
//
// POST /jobs
func (UnimplementedHandler) CreateJob(ctx context.Context, req *JobCreateDto) error {
	return ht.ErrNotImplemented
}

// CreateLibrary implements createLibrary operation.
//
// POST /libraries
func (UnimplementedHandler) CreateLibrary(ctx context.Context, req *CreateLibraryDto) (r *LibraryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMemory implements createMemory operation.
//
// POST /memories
func (UnimplementedHandler) CreateMemory(ctx context.Context, req *MemoryCreateDto) (r *MemoryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePartner implements createPartner operation.
//
// POST /partners/{id}
func (UnimplementedHandler) CreatePartner(ctx context.Context, params CreatePartnerParams) (r *PartnerResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePerson implements createPerson operation.
//
// POST /people
func (UnimplementedHandler) CreatePerson(ctx context.Context, req *PersonCreateDto) (r *PersonResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProfileImage implements createProfileImage operation.
//
// POST /users/profile-image
func (UnimplementedHandler) CreateProfileImage(ctx context.Context, req *CreateProfileImageDtoMultipart) (r *CreateProfileImageResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSharedLink implements createSharedLink operation.
//
// POST /shared-links
func (UnimplementedHandler) CreateSharedLink(ctx context.Context, req *SharedLinkCreateDto) (r *SharedLinkResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateStack implements createStack operation.
//
// POST /stacks
func (UnimplementedHandler) CreateStack(ctx context.Context, req *StackCreateDto) (r *StackResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTag implements createTag operation.
//
// POST /tags
func (UnimplementedHandler) CreateTag(ctx context.Context, req *TagCreateDto) (r *TagResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUserAdmin implements createUserAdmin operation.
//
// POST /admin/users
func (UnimplementedHandler) CreateUserAdmin(ctx context.Context, req *UserAdminCreateDto) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteActivity implements deleteActivity operation.
//
// DELETE /activities/{id}
func (UnimplementedHandler) DeleteActivity(ctx context.Context, params DeleteActivityParams) error {
	return ht.ErrNotImplemented
}

// DeleteAlbum implements deleteAlbum operation.
//
// DELETE /albums/{id}
func (UnimplementedHandler) DeleteAlbum(ctx context.Context, params DeleteAlbumParams) error {
	return ht.ErrNotImplemented
}

// DeleteAllSessions implements deleteAllSessions operation.
//
// DELETE /sessions
func (UnimplementedHandler) DeleteAllSessions(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// DeleteApiKey implements deleteApiKey operation.
//
// DELETE /api-keys/{id}
func (UnimplementedHandler) DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) error {
	return ht.ErrNotImplemented
}

// DeleteAssets implements deleteAssets operation.
//
// DELETE /assets
func (UnimplementedHandler) DeleteAssets(ctx context.Context, req *AssetBulkDeleteDto) error {
	return ht.ErrNotImplemented
}

// DeleteLibrary implements deleteLibrary operation.
//
// DELETE /libraries/{id}
func (UnimplementedHandler) DeleteLibrary(ctx context.Context, params DeleteLibraryParams) error {
	return ht.ErrNotImplemented
}

// DeleteMemory implements deleteMemory operation.
//
// DELETE /memories/{id}
func (UnimplementedHandler) DeleteMemory(ctx context.Context, params DeleteMemoryParams) error {
	return ht.ErrNotImplemented
}

// DeleteProfileImage implements deleteProfileImage operation.
//
// DELETE /users/profile-image
func (UnimplementedHandler) DeleteProfileImage(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// DeleteServerLicense implements deleteServerLicense operation.
//
// DELETE /server/license
func (UnimplementedHandler) DeleteServerLicense(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// DeleteSession implements deleteSession operation.
//
// DELETE /sessions/{id}
func (UnimplementedHandler) DeleteSession(ctx context.Context, params DeleteSessionParams) error {
	return ht.ErrNotImplemented
}

// DeleteStack implements deleteStack operation.
//
// DELETE /stacks/{id}
func (UnimplementedHandler) DeleteStack(ctx context.Context, params DeleteStackParams) error {
	return ht.ErrNotImplemented
}

// DeleteStacks implements deleteStacks operation.
//
// DELETE /stacks
func (UnimplementedHandler) DeleteStacks(ctx context.Context, req *BulkIdsDto) error {
	return ht.ErrNotImplemented
}

// DeleteTag implements deleteTag operation.
//
// DELETE /tags/{id}
func (UnimplementedHandler) DeleteTag(ctx context.Context, params DeleteTagParams) error {
	return ht.ErrNotImplemented
}

// DeleteUserAdmin implements deleteUserAdmin operation.
//
// DELETE /admin/users/{id}
func (UnimplementedHandler) DeleteUserAdmin(ctx context.Context, req *UserAdminDeleteDto, params DeleteUserAdminParams) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUserLicense implements deleteUserLicense operation.
//
// DELETE /users/me/license
func (UnimplementedHandler) DeleteUserLicense(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// DownloadArchive implements downloadArchive operation.
//
// POST /download/archive
func (UnimplementedHandler) DownloadArchive(ctx context.Context, req *AssetIdsDto, params DownloadArchiveParams) (r DownloadArchiveOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadAsset implements downloadAsset operation.
//
// GET /assets/{id}/original
func (UnimplementedHandler) DownloadAsset(ctx context.Context, params DownloadAssetParams) (r *DownloadAssetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// EmptyTrash implements emptyTrash operation.
//
// POST /trash/empty
func (UnimplementedHandler) EmptyTrash(ctx context.Context) (r *TrashResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// FinishOAuth implements finishOAuth operation.
//
// POST /oauth/callback
func (UnimplementedHandler) FinishOAuth(ctx context.Context, req *OAuthCallbackDto) (r *LoginResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// FixAuditFiles implements fixAuditFiles operation.
//
// POST /reports/fix
func (UnimplementedHandler) FixAuditFiles(ctx context.Context, req *FileReportFixDto) error {
	return ht.ErrNotImplemented
}

// GetAboutInfo implements getAboutInfo operation.
//
// GET /server/about
func (UnimplementedHandler) GetAboutInfo(ctx context.Context) (r *ServerAboutResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActivities implements getActivities operation.
//
// GET /activities
func (UnimplementedHandler) GetActivities(ctx context.Context, params GetActivitiesParams) (r []ActivityResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActivityStatistics implements getActivityStatistics operation.
//
// GET /activities/statistics
func (UnimplementedHandler) GetActivityStatistics(ctx context.Context, params GetActivityStatisticsParams) (r *ActivityStatisticsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdminOnboarding implements getAdminOnboarding operation.
//
// GET /system-metadata/admin-onboarding
func (UnimplementedHandler) GetAdminOnboarding(ctx context.Context) (r *AdminOnboardingUpdateDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlbumInfo implements getAlbumInfo operation.
//
// GET /albums/{id}
func (UnimplementedHandler) GetAlbumInfo(ctx context.Context, params GetAlbumInfoParams) (r *AlbumResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlbumStatistics implements getAlbumStatistics operation.
//
// GET /albums/statistics
func (UnimplementedHandler) GetAlbumStatistics(ctx context.Context) (r *AlbumStatisticsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllAlbums implements getAllAlbums operation.
//
// GET /albums
func (UnimplementedHandler) GetAllAlbums(ctx context.Context, params GetAllAlbumsParams) (r []AlbumResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllJobsStatus implements getAllJobsStatus operation.
//
// GET /jobs
func (UnimplementedHandler) GetAllJobsStatus(ctx context.Context) (r *AllJobStatusResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllLibraries implements getAllLibraries operation.
//
// GET /libraries
func (UnimplementedHandler) GetAllLibraries(ctx context.Context) (r []LibraryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllPeople implements getAllPeople operation.
//
// GET /people
func (UnimplementedHandler) GetAllPeople(ctx context.Context, params GetAllPeopleParams) (r *PeopleResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllSharedLinks implements getAllSharedLinks operation.
//
// GET /shared-links
func (UnimplementedHandler) GetAllSharedLinks(ctx context.Context) (r []SharedLinkResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllTags implements getAllTags operation.
//
// GET /tags
func (UnimplementedHandler) GetAllTags(ctx context.Context) (r []TagResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllUserAssetsByDeviceId implements getAllUserAssetsByDeviceId operation.
//
// Get all asset of a device that are in the database, ID only.
//
// GET /assets/device/{deviceId}
func (UnimplementedHandler) GetAllUserAssetsByDeviceId(ctx context.Context, params GetAllUserAssetsByDeviceIdParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApiKey implements getApiKey operation.
//
// GET /api-keys/{id}
func (UnimplementedHandler) GetApiKey(ctx context.Context, params GetApiKeyParams) (r *APIKeyResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApiKeys implements getApiKeys operation.
//
// GET /api-keys
func (UnimplementedHandler) GetApiKeys(ctx context.Context) (r []APIKeyResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAssetDuplicates implements getAssetDuplicates operation.
//
// GET /duplicates
func (UnimplementedHandler) GetAssetDuplicates(ctx context.Context) (r []DuplicateResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAssetInfo implements getAssetInfo operation.
//
// GET /assets/{id}
func (UnimplementedHandler) GetAssetInfo(ctx context.Context, params GetAssetInfoParams) (r *AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAssetStatistics implements getAssetStatistics operation.
//
// GET /assets/statistics
func (UnimplementedHandler) GetAssetStatistics(ctx context.Context, params GetAssetStatisticsParams) (r *AssetStatsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAssetsByCity implements getAssetsByCity operation.
//
// GET /search/cities
func (UnimplementedHandler) GetAssetsByCity(ctx context.Context) (r []AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAssetsByOriginalPath implements getAssetsByOriginalPath operation.
//
// GET /view/folder
func (UnimplementedHandler) GetAssetsByOriginalPath(ctx context.Context, params GetAssetsByOriginalPathParams) (r []AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuditDeletes implements getAuditDeletes operation.
//
// GET /audit/deletes
func (UnimplementedHandler) GetAuditDeletes(ctx context.Context, params GetAuditDeletesParams) (r *AuditDeletesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuditFiles implements getAuditFiles operation.
//
// GET /reports
func (UnimplementedHandler) GetAuditFiles(ctx context.Context) (r *FileReportDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConfig implements getConfig operation.
//
// GET /system-config
func (UnimplementedHandler) GetConfig(ctx context.Context) (r *SystemConfigDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConfigDefaults implements getConfigDefaults operation.
//
// GET /system-config/defaults
func (UnimplementedHandler) GetConfigDefaults(ctx context.Context) (r *SystemConfigDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDeltaSync implements getDeltaSync operation.
//
// POST /sync/delta-sync
func (UnimplementedHandler) GetDeltaSync(ctx context.Context, req *AssetDeltaSyncDto) (r *AssetDeltaSyncResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDownloadInfo implements getDownloadInfo operation.
//
// POST /download/info
func (UnimplementedHandler) GetDownloadInfo(ctx context.Context, req *DownloadInfoDto, params GetDownloadInfoParams) (r *DownloadResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExploreData implements getExploreData operation.
//
// GET /search/explore
func (UnimplementedHandler) GetExploreData(ctx context.Context) (r []SearchExploreResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFaces implements getFaces operation.
//
// GET /faces
func (UnimplementedHandler) GetFaces(ctx context.Context, params GetFacesParams) (r []AssetFaceResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFileChecksums implements getFileChecksums operation.
//
// POST /reports/checksum
func (UnimplementedHandler) GetFileChecksums(ctx context.Context, req *FileChecksumDto) (r []FileChecksumResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFullSyncForUser implements getFullSyncForUser operation.
//
// POST /sync/full-sync
func (UnimplementedHandler) GetFullSyncForUser(ctx context.Context, req *AssetFullSyncDto) (r []AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLibrary implements getLibrary operation.
//
// GET /libraries/{id}
func (UnimplementedHandler) GetLibrary(ctx context.Context, params GetLibraryParams) (r *LibraryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLibraryStatistics implements getLibraryStatistics operation.
//
// GET /libraries/{id}/statistics
func (UnimplementedHandler) GetLibraryStatistics(ctx context.Context, params GetLibraryStatisticsParams) (r *LibraryStatsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMapMarkers implements getMapMarkers operation.
//
// GET /map/markers
func (UnimplementedHandler) GetMapMarkers(ctx context.Context, params GetMapMarkersParams) (r []MapMarkerResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemory implements getMemory operation.
//
// GET /memories/{id}
func (UnimplementedHandler) GetMemory(ctx context.Context, params GetMemoryParams) (r *MemoryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemoryLane implements getMemoryLane operation.
//
// GET /assets/memory-lane
func (UnimplementedHandler) GetMemoryLane(ctx context.Context, params GetMemoryLaneParams) (r []MemoryLaneResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyPreferences implements getMyPreferences operation.
//
// GET /users/me/preferences
func (UnimplementedHandler) GetMyPreferences(ctx context.Context) (r *UserPreferencesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMySharedLink implements getMySharedLink operation.
//
// GET /shared-links/me
func (UnimplementedHandler) GetMySharedLink(ctx context.Context, params GetMySharedLinkParams) (r *SharedLinkResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyUser implements getMyUser operation.
//
// GET /users/me
func (UnimplementedHandler) GetMyUser(ctx context.Context) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPartners implements getPartners operation.
//
// GET /partners
func (UnimplementedHandler) GetPartners(ctx context.Context, params GetPartnersParams) (r []PartnerResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPerson implements getPerson operation.
//
// GET /people/{id}
func (UnimplementedHandler) GetPerson(ctx context.Context, params GetPersonParams) (r *PersonResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPersonStatistics implements getPersonStatistics operation.
//
// GET /people/{id}/statistics
func (UnimplementedHandler) GetPersonStatistics(ctx context.Context, params GetPersonStatisticsParams) (r *PersonStatisticsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPersonThumbnail implements getPersonThumbnail operation.
//
// GET /people/{id}/thumbnail
func (UnimplementedHandler) GetPersonThumbnail(ctx context.Context, params GetPersonThumbnailParams) (r GetPersonThumbnailOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProfileImage implements getProfileImage operation.
//
// GET /users/{id}/profile-image
func (UnimplementedHandler) GetProfileImage(ctx context.Context, params GetProfileImageParams) (r GetProfileImageOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRandom implements getRandom operation.
//
// This property was deprecated in v1.116.0.
//
// Deprecated: schema marks this operation as deprecated.
//
// GET /assets/random
func (UnimplementedHandler) GetRandom(ctx context.Context, params GetRandomParams) (r []AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReverseGeocodingState implements getReverseGeocodingState operation.
//
// GET /system-metadata/reverse-geocoding-state
func (UnimplementedHandler) GetReverseGeocodingState(ctx context.Context) (r *ReverseGeocodingStateResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSearchSuggestions implements getSearchSuggestions operation.
//
// GET /search/suggestions
func (UnimplementedHandler) GetSearchSuggestions(ctx context.Context, params GetSearchSuggestionsParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerConfig implements getServerConfig operation.
//
// GET /server/config
func (UnimplementedHandler) GetServerConfig(ctx context.Context) (r *ServerConfigDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerFeatures implements getServerFeatures operation.
//
// GET /server/features
func (UnimplementedHandler) GetServerFeatures(ctx context.Context) (r *ServerFeaturesDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerLicense implements getServerLicense operation.
//
// GET /server/license
func (UnimplementedHandler) GetServerLicense(ctx context.Context) (r GetServerLicenseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerStatistics implements getServerStatistics operation.
//
// GET /server/statistics
func (UnimplementedHandler) GetServerStatistics(ctx context.Context) (r *ServerStatsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerVersion implements getServerVersion operation.
//
// GET /server/version
func (UnimplementedHandler) GetServerVersion(ctx context.Context) (r *ServerVersionResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSessions implements getSessions operation.
//
// GET /sessions
func (UnimplementedHandler) GetSessions(ctx context.Context) (r []SessionResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSharedLinkById implements getSharedLinkById operation.
//
// GET /shared-links/{id}
func (UnimplementedHandler) GetSharedLinkById(ctx context.Context, params GetSharedLinkByIdParams) (r *SharedLinkResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStack implements getStack operation.
//
// GET /stacks/{id}
func (UnimplementedHandler) GetStack(ctx context.Context, params GetStackParams) (r *StackResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStorage implements getStorage operation.
//
// GET /server/storage
func (UnimplementedHandler) GetStorage(ctx context.Context) (r *ServerStorageResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStorageTemplateOptions implements getStorageTemplateOptions operation.
//
// GET /system-config/storage-template-options
func (UnimplementedHandler) GetStorageTemplateOptions(ctx context.Context) (r *SystemConfigTemplateStorageOptionDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSupportedMediaTypes implements getSupportedMediaTypes operation.
//
// GET /server/media-types
func (UnimplementedHandler) GetSupportedMediaTypes(ctx context.Context) (r *ServerMediaTypesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTagById implements getTagById operation.
//
// GET /tags/{id}
func (UnimplementedHandler) GetTagById(ctx context.Context, params GetTagByIdParams) (r *TagResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTheme implements getTheme operation.
//
// GET /server/theme
func (UnimplementedHandler) GetTheme(ctx context.Context) (r *ServerThemeDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimeBucket implements getTimeBucket operation.
//
// GET /timeline/bucket
func (UnimplementedHandler) GetTimeBucket(ctx context.Context, params GetTimeBucketParams) (r []AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimeBuckets implements getTimeBuckets operation.
//
// GET /timeline/buckets
func (UnimplementedHandler) GetTimeBuckets(ctx context.Context, params GetTimeBucketsParams) (r []TimeBucketResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUniqueOriginalPaths implements getUniqueOriginalPaths operation.
//
// GET /view/folder/unique-paths
func (UnimplementedHandler) GetUniqueOriginalPaths(ctx context.Context) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// GET /users/{id}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r *UserResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserAdmin implements getUserAdmin operation.
//
// GET /admin/users/{id}
func (UnimplementedHandler) GetUserAdmin(ctx context.Context, params GetUserAdminParams) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserLicense implements getUserLicense operation.
//
// GET /users/me/license
func (UnimplementedHandler) GetUserLicense(ctx context.Context) (r *LicenseResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserPreferencesAdmin implements getUserPreferencesAdmin operation.
//
// GET /admin/users/{id}/preferences
func (UnimplementedHandler) GetUserPreferencesAdmin(ctx context.Context, params GetUserPreferencesAdminParams) (r *UserPreferencesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVersionHistory implements getVersionHistory operation.
//
// GET /server/version-history
func (UnimplementedHandler) GetVersionHistory(ctx context.Context) (r []ServerVersionHistoryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// LinkOAuthAccount implements linkOAuthAccount operation.
//
// POST /oauth/link
func (UnimplementedHandler) LinkOAuthAccount(ctx context.Context, req *OAuthCallbackDto) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// POST /auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginCredentialDto) (r *LoginResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// POST /auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) (r *LogoutResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// MergePerson implements mergePerson operation.
//
// POST /people/{id}/merge
func (UnimplementedHandler) MergePerson(ctx context.Context, req *MergePersonDto, params MergePersonParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// PingServer implements pingServer operation.
//
// GET /server/ping
func (UnimplementedHandler) PingServer(ctx context.Context) (r *ServerPingResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// PlayAssetVideo implements playAssetVideo operation.
//
// GET /assets/{id}/video/playback
func (UnimplementedHandler) PlayAssetVideo(ctx context.Context, params PlayAssetVideoParams) (r PlayAssetVideoOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ReassignFaces implements reassignFaces operation.
//
// PUT /people/{id}/reassign
func (UnimplementedHandler) ReassignFaces(ctx context.Context, req *AssetFaceUpdateDto, params ReassignFacesParams) (r []PersonResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// ReassignFacesById implements reassignFacesById operation.
//
// PUT /faces/{id}
func (UnimplementedHandler) ReassignFacesById(ctx context.Context, req *FaceDto, params ReassignFacesByIdParams) (r *PersonResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RedirectOAuthToMobile implements redirectOAuthToMobile operation.
//
// GET /oauth/mobile-redirect
func (UnimplementedHandler) RedirectOAuthToMobile(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// RemoveAssetFromAlbum implements removeAssetFromAlbum operation.
//
// DELETE /albums/{id}/assets
func (UnimplementedHandler) RemoveAssetFromAlbum(ctx context.Context, req *BulkIdsDto, params RemoveAssetFromAlbumParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveMemoryAssets implements removeMemoryAssets operation.
//
// DELETE /memories/{id}/assets
func (UnimplementedHandler) RemoveMemoryAssets(ctx context.Context, req *BulkIdsDto, params RemoveMemoryAssetsParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RemovePartner implements removePartner operation.
//
// DELETE /partners/{id}
func (UnimplementedHandler) RemovePartner(ctx context.Context, params RemovePartnerParams) error {
	return ht.ErrNotImplemented
}

// RemoveSharedLink implements removeSharedLink operation.
//
// DELETE /shared-links/{id}
func (UnimplementedHandler) RemoveSharedLink(ctx context.Context, params RemoveSharedLinkParams) error {
	return ht.ErrNotImplemented
}

// RemoveSharedLinkAssets implements removeSharedLinkAssets operation.
//
// DELETE /shared-links/{id}/assets
func (UnimplementedHandler) RemoveSharedLinkAssets(ctx context.Context, req *AssetIdsDto, params RemoveSharedLinkAssetsParams) (r []AssetIdsResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveUserFromAlbum implements removeUserFromAlbum operation.
//
// DELETE /albums/{id}/user/{userId}
func (UnimplementedHandler) RemoveUserFromAlbum(ctx context.Context, params RemoveUserFromAlbumParams) error {
	return ht.ErrNotImplemented
}

// ReplaceAsset implements replaceAsset operation.
//
// Replace the asset with new file, without changing its id.
//
// PUT /assets/{id}/original
func (UnimplementedHandler) ReplaceAsset(ctx context.Context, req *AssetMediaReplaceDtoMultipart, params ReplaceAssetParams) (r *AssetMediaResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreAssets implements restoreAssets operation.
//
// POST /trash/restore/assets
func (UnimplementedHandler) RestoreAssets(ctx context.Context, req *BulkIdsDto) (r *TrashResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreTrash implements restoreTrash operation.
//
// POST /trash/restore
func (UnimplementedHandler) RestoreTrash(ctx context.Context) (r *TrashResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreUserAdmin implements restoreUserAdmin operation.
//
// POST /admin/users/{id}/restore
func (UnimplementedHandler) RestoreUserAdmin(ctx context.Context, params RestoreUserAdminParams) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// ReverseGeocode implements reverseGeocode operation.
//
// GET /map/reverse-geocode
func (UnimplementedHandler) ReverseGeocode(ctx context.Context, params ReverseGeocodeParams) (r []MapReverseGeocodeResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// RunAssetJobs implements runAssetJobs operation.
//
// POST /assets/jobs
func (UnimplementedHandler) RunAssetJobs(ctx context.Context, req *AssetJobsDto) error {
	return ht.ErrNotImplemented
}

// ScanLibrary implements scanLibrary operation.
//
// POST /libraries/{id}/scan
func (UnimplementedHandler) ScanLibrary(ctx context.Context, params ScanLibraryParams) error {
	return ht.ErrNotImplemented
}

// SearchMemories implements searchMemories operation.
//
// GET /memories
func (UnimplementedHandler) SearchMemories(ctx context.Context) (r []MemoryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchMetadata implements searchMetadata operation.
//
// POST /search/metadata
func (UnimplementedHandler) SearchMetadata(ctx context.Context, req *MetadataSearchDto) (r *SearchResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchPerson implements searchPerson operation.
//
// GET /search/person
func (UnimplementedHandler) SearchPerson(ctx context.Context, params SearchPersonParams) (r []PersonResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchPlaces implements searchPlaces operation.
//
// GET /search/places
func (UnimplementedHandler) SearchPlaces(ctx context.Context, params SearchPlacesParams) (r []PlacesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchRandom implements searchRandom operation.
//
// POST /search/random
func (UnimplementedHandler) SearchRandom(ctx context.Context, req *RandomSearchDto) (r []AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchSmart implements searchSmart operation.
//
// POST /search/smart
func (UnimplementedHandler) SearchSmart(ctx context.Context, req *SmartSearchDto) (r *SearchResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchStacks implements searchStacks operation.
//
// GET /stacks
func (UnimplementedHandler) SearchStacks(ctx context.Context, params SearchStacksParams) (r []StackResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchUsers implements searchUsers operation.
//
// GET /users
func (UnimplementedHandler) SearchUsers(ctx context.Context) (r []UserResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchUsersAdmin implements searchUsersAdmin operation.
//
// GET /admin/users
func (UnimplementedHandler) SearchUsersAdmin(ctx context.Context, params SearchUsersAdminParams) (r []UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SendJobCommand implements sendJobCommand operation.
//
// PUT /jobs/{id}
func (UnimplementedHandler) SendJobCommand(ctx context.Context, req *JobCommandDto, params SendJobCommandParams) (r *JobStatusDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SendTestEmail implements sendTestEmail operation.
//
// POST /notifications/test-email
func (UnimplementedHandler) SendTestEmail(ctx context.Context, req *SystemConfigSmtpDto) (r *TestEmailResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SetServerLicense implements setServerLicense operation.
//
// PUT /server/license
func (UnimplementedHandler) SetServerLicense(ctx context.Context, req *LicenseKeyDto) (r *LicenseResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SetUserLicense implements setUserLicense operation.
//
// PUT /users/me/license
func (UnimplementedHandler) SetUserLicense(ctx context.Context, req *LicenseKeyDto) (r *LicenseResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// SignUpAdmin implements signUpAdmin operation.
//
// POST /auth/admin-sign-up
func (UnimplementedHandler) SignUpAdmin(ctx context.Context, req *SignUpDto) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// StartOAuth implements startOAuth operation.
//
// POST /oauth/authorize
func (UnimplementedHandler) StartOAuth(ctx context.Context, req *OAuthConfigDto) (r *OAuthAuthorizeResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// TagAssets implements tagAssets operation.
//
// PUT /tags/{id}/assets
func (UnimplementedHandler) TagAssets(ctx context.Context, req *BulkIdsDto, params TagAssetsParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UnlinkOAuthAccount implements unlinkOAuthAccount operation.
//
// POST /oauth/unlink
func (UnimplementedHandler) UnlinkOAuthAccount(ctx context.Context) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UntagAssets implements untagAssets operation.
//
// DELETE /tags/{id}/assets
func (UnimplementedHandler) UntagAssets(ctx context.Context, req *BulkIdsDto, params UntagAssetsParams) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAdminOnboarding implements updateAdminOnboarding operation.
//
// POST /system-metadata/admin-onboarding
func (UnimplementedHandler) UpdateAdminOnboarding(ctx context.Context, req *AdminOnboardingUpdateDto) error {
	return ht.ErrNotImplemented
}

// UpdateAlbumInfo implements updateAlbumInfo operation.
//
// PATCH /albums/{id}
func (UnimplementedHandler) UpdateAlbumInfo(ctx context.Context, req *UpdateAlbumDto, params UpdateAlbumInfoParams) (r *AlbumResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAlbumUser implements updateAlbumUser operation.
//
// PUT /albums/{id}/user/{userId}
func (UnimplementedHandler) UpdateAlbumUser(ctx context.Context, req *UpdateAlbumUserDto, params UpdateAlbumUserParams) error {
	return ht.ErrNotImplemented
}

// UpdateApiKey implements updateApiKey operation.
//
// PUT /api-keys/{id}
func (UnimplementedHandler) UpdateApiKey(ctx context.Context, req *APIKeyUpdateDto, params UpdateApiKeyParams) (r *APIKeyResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAsset implements updateAsset operation.
//
// PUT /assets/{id}
func (UnimplementedHandler) UpdateAsset(ctx context.Context, req *UpdateAssetDto, params UpdateAssetParams) (r *AssetResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAssets implements updateAssets operation.
//
// PUT /assets
func (UnimplementedHandler) UpdateAssets(ctx context.Context, req *AssetBulkUpdateDto) error {
	return ht.ErrNotImplemented
}

// UpdateConfig implements updateConfig operation.
//
// PUT /system-config
func (UnimplementedHandler) UpdateConfig(ctx context.Context, req *SystemConfigDto) (r *SystemConfigDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateLibrary implements updateLibrary operation.
//
// PUT /libraries/{id}
func (UnimplementedHandler) UpdateLibrary(ctx context.Context, req *UpdateLibraryDto, params UpdateLibraryParams) (r *LibraryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMemory implements updateMemory operation.
//
// PUT /memories/{id}
func (UnimplementedHandler) UpdateMemory(ctx context.Context, req *MemoryUpdateDto, params UpdateMemoryParams) (r *MemoryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMyPreferences implements updateMyPreferences operation.
//
// PUT /users/me/preferences
func (UnimplementedHandler) UpdateMyPreferences(ctx context.Context, req *UserPreferencesUpdateDto) (r *UserPreferencesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMyUser implements updateMyUser operation.
//
// PUT /users/me
func (UnimplementedHandler) UpdateMyUser(ctx context.Context, req *UserUpdateMeDto) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePartner implements updatePartner operation.
//
// PUT /partners/{id}
func (UnimplementedHandler) UpdatePartner(ctx context.Context, req *UpdatePartnerDto, params UpdatePartnerParams) (r *PartnerResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePeople implements updatePeople operation.
//
// PUT /people
func (UnimplementedHandler) UpdatePeople(ctx context.Context, req *PeopleUpdateDto) (r []BulkIdResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePerson implements updatePerson operation.
//
// PUT /people/{id}
func (UnimplementedHandler) UpdatePerson(ctx context.Context, req *PersonUpdateDto, params UpdatePersonParams) (r *PersonResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSharedLink implements updateSharedLink operation.
//
// PATCH /shared-links/{id}
func (UnimplementedHandler) UpdateSharedLink(ctx context.Context, req *SharedLinkEditDto, params UpdateSharedLinkParams) (r *SharedLinkResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStack implements updateStack operation.
//
// PUT /stacks/{id}
func (UnimplementedHandler) UpdateStack(ctx context.Context, req *StackUpdateDto, params UpdateStackParams) (r *StackResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTag implements updateTag operation.
//
// PUT /tags/{id}
func (UnimplementedHandler) UpdateTag(ctx context.Context, req *TagUpdateDto, params UpdateTagParams) (r *TagResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserAdmin implements updateUserAdmin operation.
//
// PUT /admin/users/{id}
func (UnimplementedHandler) UpdateUserAdmin(ctx context.Context, req *UserAdminUpdateDto, params UpdateUserAdminParams) (r *UserAdminResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserPreferencesAdmin implements updateUserPreferencesAdmin operation.
//
// PUT /admin/users/{id}/preferences
func (UnimplementedHandler) UpdateUserPreferencesAdmin(ctx context.Context, req *UserPreferencesUpdateDto, params UpdateUserPreferencesAdminParams) (r *UserPreferencesResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadAsset implements uploadAsset operation.
//
// POST /assets
func (UnimplementedHandler) UploadAsset(ctx context.Context, req *AssetMediaCreateDtoMultipart, params UploadAssetParams) (r *AssetMediaResponseDtoStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertTags implements upsertTags operation.
//
// PUT /tags
func (UnimplementedHandler) UpsertTags(ctx context.Context, req *TagUpsertDto) (r []TagResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// Validate implements validate operation.
//
// POST /libraries/{id}/validate
func (UnimplementedHandler) Validate(ctx context.Context, req *ValidateLibraryDto, params ValidateParams) (r *ValidateLibraryResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateAccessToken implements validateAccessToken operation.
//
// POST /auth/validateToken
func (UnimplementedHandler) ValidateAccessToken(ctx context.Context) (r *ValidateAccessTokenResponseDto, _ error) {
	return r, ht.ErrNotImplemented
}

// ViewAsset implements viewAsset operation.
//
// GET /assets/{id}/thumbnail
func (UnimplementedHandler) ViewAsset(ctx context.Context, params ViewAssetParams) (r ViewAssetOK, _ error) {
	return r, ht.ErrNotImplemented
}
