// Code generated by ogen, DO NOT EDIT.

package oapi

// setDefaults set default value of fields.
func (s *DownloadResponse) setDefaults() {
	{
		val := bool(false)
		s.IncludeEmbeddedVideos = val
	}
}

// setDefaults set default value of fields.
func (s *ExifResponseDto) setDefaults() {
	{
		s.City.Null = true
	}
	{
		s.Country.Null = true
	}
	{
		s.DateTimeOriginal.Null = true
	}
	{
		s.Description.Null = true
	}
	{
		s.ExifImageHeight.Null = true
	}
	{
		s.ExifImageWidth.Null = true
	}
	{
		s.ExposureTime.Null = true
	}
	{
		s.FNumber.Null = true
	}
	{
		s.FileSizeInByte.Null = true
	}
	{
		s.FocalLength.Null = true
	}
	{
		s.Iso.Null = true
	}
	{
		s.Latitude.Null = true
	}
	{
		s.LensModel.Null = true
	}
	{
		s.Longitude.Null = true
	}
	{
		s.Make.Null = true
	}
	{
		s.Model.Null = true
	}
	{
		s.ModifyDate.Null = true
	}
	{
		s.Orientation.Null = true
	}
	{
		s.ProjectionType.Null = true
	}
	{
		s.Rating.Null = true
	}
	{
		s.State.Null = true
	}
	{
		s.TimeZone.Null = true
	}
}

// setDefaults set default value of fields.
func (s *FoldersResponse) setDefaults() {
	{
		val := bool(false)
		s.Enabled = val
	}
	{
		val := bool(false)
		s.SidebarWeb = val
	}
}

// setDefaults set default value of fields.
func (s *LibraryStatsResponseDto) setDefaults() {
	{
		val := int(0)
		s.Photos = val
	}
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int64(0)
		s.Usage = val
	}
	{
		val := int(0)
		s.Videos = val
	}
}

// setDefaults set default value of fields.
func (s *MemoriesResponse) setDefaults() {
	{
		val := bool(true)
		s.Enabled = val
	}
}

// setDefaults set default value of fields.
func (s *MetadataSearchDto) setDefaults() {
	{
		val := bool(false)
		s.WithArchived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PeopleResponse) setDefaults() {
	{
		val := bool(true)
		s.Enabled = val
	}
	{
		val := bool(false)
		s.SidebarWeb = val
	}
}

// setDefaults set default value of fields.
func (s *RandomSearchDto) setDefaults() {
	{
		val := bool(false)
		s.WithArchived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RatingsResponse) setDefaults() {
	{
		val := bool(false)
		s.Enabled = val
	}
}

// setDefaults set default value of fields.
func (s *ServerStatsResponseDto) setDefaults() {
	{
		val := int(0)
		s.Photos = val
	}
	{
		val := int64(0)
		s.Usage = val
	}
	{
		val := int(0)
		s.Videos = val
	}
}

// setDefaults set default value of fields.
func (s *SharedLinkCreateDto) setDefaults() {
	{
		val := bool(true)
		s.AllowDownload.SetTo(val)
	}
	{
		s.ExpiresAt.Null = true
	}
	{
		val := bool(true)
		s.ShowMetadata.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SmartSearchDto) setDefaults() {
	{
		val := bool(false)
		s.WithArchived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TagsResponse) setDefaults() {
	{
		val := bool(true)
		s.Enabled = val
	}
	{
		val := bool(true)
		s.SidebarWeb = val
	}
}

// setDefaults set default value of fields.
func (s *ValidateLibraryImportPathResponseDto) setDefaults() {
	{
		val := bool(false)
		s.IsValid = val
	}
}
