// Code generated by ogen, DO NOT EDIT.

package oapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAPIKey handles api_key security.
	HandleAPIKey(ctx context.Context, operationName string, t APIKey) (context.Context, error)
	// HandleBearer handles bearer security.
	HandleBearer(ctx context.Context, operationName string, t Bearer) (context.Context, error)
	// HandleCookie handles cookie security.
	HandleCookie(ctx context.Context, operationName string, t Cookie) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityAPIKey(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t APIKey
	const parameterName = "x-api-key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	rctx, err := s.sec.HandleAPIKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
func (s *Server) securityBearer(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t Bearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	rctx, err := s.sec.HandleBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
func (s *Server) securityCookie(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t Cookie
	const parameterName = "immich_access_token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	rctx, err := s.sec.HandleCookie(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// APIKey provides api_key security value.
	APIKey(ctx context.Context, operationName string) (APIKey, error)
	// Bearer provides bearer security value.
	Bearer(ctx context.Context, operationName string) (Bearer, error)
	// Cookie provides cookie security value.
	Cookie(ctx context.Context, operationName string) (Cookie, error)
}

func (s *Client) securityAPIKey(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.APIKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"APIKey\"")
	}
	req.Header.Set("x-api-key", t.APIKey)
	return nil
}
func (s *Client) securityBearer(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.Bearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Bearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityCookie(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.Cookie(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Cookie\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "immich_access_token",
		Value: t.APIKey,
	})
	return nil
}
