// Code generated by ogen, DO NOT EDIT.

package oapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddAssetsToAlbum implements addAssetsToAlbum operation.
	//
	// PUT /albums/{id}/assets
	AddAssetsToAlbum(ctx context.Context, req *BulkIdsDto, params AddAssetsToAlbumParams) ([]BulkIdResponseDto, error)
	// AddMemoryAssets implements addMemoryAssets operation.
	//
	// PUT /memories/{id}/assets
	AddMemoryAssets(ctx context.Context, req *BulkIdsDto, params AddMemoryAssetsParams) ([]BulkIdResponseDto, error)
	// AddSharedLinkAssets implements addSharedLinkAssets operation.
	//
	// PUT /shared-links/{id}/assets
	AddSharedLinkAssets(ctx context.Context, req *AssetIdsDto, params AddSharedLinkAssetsParams) ([]AssetIdsResponseDto, error)
	// AddUsersToAlbum implements addUsersToAlbum operation.
	//
	// PUT /albums/{id}/users
	AddUsersToAlbum(ctx context.Context, req *AddUsersDto, params AddUsersToAlbumParams) (*AlbumResponseDto, error)
	// BulkTagAssets implements bulkTagAssets operation.
	//
	// PUT /tags/assets
	BulkTagAssets(ctx context.Context, req *TagBulkAssetsDto) (*TagBulkAssetsResponseDto, error)
	// ChangePassword implements changePassword operation.
	//
	// POST /auth/change-password
	ChangePassword(ctx context.Context, req *ChangePasswordDto) (*UserAdminResponseDto, error)
	// CheckBulkUpload implements checkBulkUpload operation.
	//
	// Checks if assets exist by checksums.
	//
	// POST /assets/bulk-upload-check
	CheckBulkUpload(ctx context.Context, req *AssetBulkUploadCheckDto) (*AssetBulkUploadCheckResponseDto, error)
	// CheckExistingAssets implements checkExistingAssets operation.
	//
	// Checks if multiple assets exist on the server and returns all existing - used by background backup.
	//
	// POST /assets/exist
	CheckExistingAssets(ctx context.Context, req *CheckExistingAssetsDto) (*CheckExistingAssetsResponseDto, error)
	// CreateActivity implements createActivity operation.
	//
	// POST /activities
	CreateActivity(ctx context.Context, req *ActivityCreateDto) (*ActivityResponseDto, error)
	// CreateAlbum implements createAlbum operation.
	//
	// POST /albums
	CreateAlbum(ctx context.Context, req *CreateAlbumDto) (*AlbumResponseDto, error)
	// CreateApiKey implements createApiKey operation.
	//
	// POST /api-keys
	CreateApiKey(ctx context.Context, req *APIKeyCreateDto) (*APIKeyCreateResponseDto, error)
	// CreateJob implements createJob operation.
	//
	// POST /jobs
	CreateJob(ctx context.Context, req *JobCreateDto) error
	// CreateLibrary implements createLibrary operation.
	//
	// POST /libraries
	CreateLibrary(ctx context.Context, req *CreateLibraryDto) (*LibraryResponseDto, error)
	// CreateMemory implements createMemory operation.
	//
	// POST /memories
	CreateMemory(ctx context.Context, req *MemoryCreateDto) (*MemoryResponseDto, error)
	// CreatePartner implements createPartner operation.
	//
	// POST /partners/{id}
	CreatePartner(ctx context.Context, params CreatePartnerParams) (*PartnerResponseDto, error)
	// CreatePerson implements createPerson operation.
	//
	// POST /people
	CreatePerson(ctx context.Context, req *PersonCreateDto) (*PersonResponseDto, error)
	// CreateProfileImage implements createProfileImage operation.
	//
	// POST /users/profile-image
	CreateProfileImage(ctx context.Context, req *CreateProfileImageDtoMultipart) (*CreateProfileImageResponseDto, error)
	// CreateSharedLink implements createSharedLink operation.
	//
	// POST /shared-links
	CreateSharedLink(ctx context.Context, req *SharedLinkCreateDto) (*SharedLinkResponseDto, error)
	// CreateStack implements createStack operation.
	//
	// POST /stacks
	CreateStack(ctx context.Context, req *StackCreateDto) (*StackResponseDto, error)
	// CreateTag implements createTag operation.
	//
	// POST /tags
	CreateTag(ctx context.Context, req *TagCreateDto) (*TagResponseDto, error)
	// CreateUserAdmin implements createUserAdmin operation.
	//
	// POST /admin/users
	CreateUserAdmin(ctx context.Context, req *UserAdminCreateDto) (*UserAdminResponseDto, error)
	// DeleteActivity implements deleteActivity operation.
	//
	// DELETE /activities/{id}
	DeleteActivity(ctx context.Context, params DeleteActivityParams) error
	// DeleteAlbum implements deleteAlbum operation.
	//
	// DELETE /albums/{id}
	DeleteAlbum(ctx context.Context, params DeleteAlbumParams) error
	// DeleteAllSessions implements deleteAllSessions operation.
	//
	// DELETE /sessions
	DeleteAllSessions(ctx context.Context) error
	// DeleteApiKey implements deleteApiKey operation.
	//
	// DELETE /api-keys/{id}
	DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) error
	// DeleteAssets implements deleteAssets operation.
	//
	// DELETE /assets
	DeleteAssets(ctx context.Context, req *AssetBulkDeleteDto) error
	// DeleteLibrary implements deleteLibrary operation.
	//
	// DELETE /libraries/{id}
	DeleteLibrary(ctx context.Context, params DeleteLibraryParams) error
	// DeleteMemory implements deleteMemory operation.
	//
	// DELETE /memories/{id}
	DeleteMemory(ctx context.Context, params DeleteMemoryParams) error
	// DeleteProfileImage implements deleteProfileImage operation.
	//
	// DELETE /users/profile-image
	DeleteProfileImage(ctx context.Context) error
	// DeleteServerLicense implements deleteServerLicense operation.
	//
	// DELETE /server/license
	DeleteServerLicense(ctx context.Context) error
	// DeleteSession implements deleteSession operation.
	//
	// DELETE /sessions/{id}
	DeleteSession(ctx context.Context, params DeleteSessionParams) error
	// DeleteStack implements deleteStack operation.
	//
	// DELETE /stacks/{id}
	DeleteStack(ctx context.Context, params DeleteStackParams) error
	// DeleteStacks implements deleteStacks operation.
	//
	// DELETE /stacks
	DeleteStacks(ctx context.Context, req *BulkIdsDto) error
	// DeleteTag implements deleteTag operation.
	//
	// DELETE /tags/{id}
	DeleteTag(ctx context.Context, params DeleteTagParams) error
	// DeleteUserAdmin implements deleteUserAdmin operation.
	//
	// DELETE /admin/users/{id}
	DeleteUserAdmin(ctx context.Context, req *UserAdminDeleteDto, params DeleteUserAdminParams) (*UserAdminResponseDto, error)
	// DeleteUserLicense implements deleteUserLicense operation.
	//
	// DELETE /users/me/license
	DeleteUserLicense(ctx context.Context) error
	// DownloadArchive implements downloadArchive operation.
	//
	// POST /download/archive
	DownloadArchive(ctx context.Context, req *AssetIdsDto, params DownloadArchiveParams) (DownloadArchiveOK, error)
	// DownloadAsset implements downloadAsset operation.
	//
	// GET /assets/{id}/original
	DownloadAsset(ctx context.Context, params DownloadAssetParams) (*DownloadAssetOKHeaders, error)
	// EmptyTrash implements emptyTrash operation.
	//
	// POST /trash/empty
	EmptyTrash(ctx context.Context) (*TrashResponseDto, error)
	// FinishOAuth implements finishOAuth operation.
	//
	// POST /oauth/callback
	FinishOAuth(ctx context.Context, req *OAuthCallbackDto) (*LoginResponseDto, error)
	// FixAuditFiles implements fixAuditFiles operation.
	//
	// POST /reports/fix
	FixAuditFiles(ctx context.Context, req *FileReportFixDto) error
	// GetAboutInfo implements getAboutInfo operation.
	//
	// GET /server/about
	GetAboutInfo(ctx context.Context) (*ServerAboutResponseDto, error)
	// GetActivities implements getActivities operation.
	//
	// GET /activities
	GetActivities(ctx context.Context, params GetActivitiesParams) ([]ActivityResponseDto, error)
	// GetActivityStatistics implements getActivityStatistics operation.
	//
	// GET /activities/statistics
	GetActivityStatistics(ctx context.Context, params GetActivityStatisticsParams) (*ActivityStatisticsResponseDto, error)
	// GetAdminOnboarding implements getAdminOnboarding operation.
	//
	// GET /system-metadata/admin-onboarding
	GetAdminOnboarding(ctx context.Context) (*AdminOnboardingUpdateDto, error)
	// GetAlbumInfo implements getAlbumInfo operation.
	//
	// GET /albums/{id}
	GetAlbumInfo(ctx context.Context, params GetAlbumInfoParams) (*AlbumResponseDto, error)
	// GetAlbumStatistics implements getAlbumStatistics operation.
	//
	// GET /albums/statistics
	GetAlbumStatistics(ctx context.Context) (*AlbumStatisticsResponseDto, error)
	// GetAllAlbums implements getAllAlbums operation.
	//
	// GET /albums
	GetAllAlbums(ctx context.Context, params GetAllAlbumsParams) ([]AlbumResponseDto, error)
	// GetAllJobsStatus implements getAllJobsStatus operation.
	//
	// GET /jobs
	GetAllJobsStatus(ctx context.Context) (*AllJobStatusResponseDto, error)
	// GetAllLibraries implements getAllLibraries operation.
	//
	// GET /libraries
	GetAllLibraries(ctx context.Context) ([]LibraryResponseDto, error)
	// GetAllPeople implements getAllPeople operation.
	//
	// GET /people
	GetAllPeople(ctx context.Context, params GetAllPeopleParams) (*PeopleResponseDto, error)
	// GetAllSharedLinks implements getAllSharedLinks operation.
	//
	// GET /shared-links
	GetAllSharedLinks(ctx context.Context) ([]SharedLinkResponseDto, error)
	// GetAllTags implements getAllTags operation.
	//
	// GET /tags
	GetAllTags(ctx context.Context) ([]TagResponseDto, error)
	// GetAllUserAssetsByDeviceId implements getAllUserAssetsByDeviceId operation.
	//
	// Get all asset of a device that are in the database, ID only.
	//
	// GET /assets/device/{deviceId}
	GetAllUserAssetsByDeviceId(ctx context.Context, params GetAllUserAssetsByDeviceIdParams) ([]string, error)
	// GetApiKey implements getApiKey operation.
	//
	// GET /api-keys/{id}
	GetApiKey(ctx context.Context, params GetApiKeyParams) (*APIKeyResponseDto, error)
	// GetApiKeys implements getApiKeys operation.
	//
	// GET /api-keys
	GetApiKeys(ctx context.Context) ([]APIKeyResponseDto, error)
	// GetAssetDuplicates implements getAssetDuplicates operation.
	//
	// GET /duplicates
	GetAssetDuplicates(ctx context.Context) ([]DuplicateResponseDto, error)
	// GetAssetInfo implements getAssetInfo operation.
	//
	// GET /assets/{id}
	GetAssetInfo(ctx context.Context, params GetAssetInfoParams) (*AssetResponseDto, error)
	// GetAssetStatistics implements getAssetStatistics operation.
	//
	// GET /assets/statistics
	GetAssetStatistics(ctx context.Context, params GetAssetStatisticsParams) (*AssetStatsResponseDto, error)
	// GetAssetsByCity implements getAssetsByCity operation.
	//
	// GET /search/cities
	GetAssetsByCity(ctx context.Context) ([]AssetResponseDto, error)
	// GetAssetsByOriginalPath implements getAssetsByOriginalPath operation.
	//
	// GET /view/folder
	GetAssetsByOriginalPath(ctx context.Context, params GetAssetsByOriginalPathParams) ([]AssetResponseDto, error)
	// GetAuditDeletes implements getAuditDeletes operation.
	//
	// GET /audit/deletes
	GetAuditDeletes(ctx context.Context, params GetAuditDeletesParams) (*AuditDeletesResponseDto, error)
	// GetAuditFiles implements getAuditFiles operation.
	//
	// GET /reports
	GetAuditFiles(ctx context.Context) (*FileReportDto, error)
	// GetConfig implements getConfig operation.
	//
	// GET /system-config
	GetConfig(ctx context.Context) (*SystemConfigDto, error)
	// GetConfigDefaults implements getConfigDefaults operation.
	//
	// GET /system-config/defaults
	GetConfigDefaults(ctx context.Context) (*SystemConfigDto, error)
	// GetDeltaSync implements getDeltaSync operation.
	//
	// POST /sync/delta-sync
	GetDeltaSync(ctx context.Context, req *AssetDeltaSyncDto) (*AssetDeltaSyncResponseDto, error)
	// GetDownloadInfo implements getDownloadInfo operation.
	//
	// POST /download/info
	GetDownloadInfo(ctx context.Context, req *DownloadInfoDto, params GetDownloadInfoParams) (*DownloadResponseDto, error)
	// GetExploreData implements getExploreData operation.
	//
	// GET /search/explore
	GetExploreData(ctx context.Context) ([]SearchExploreResponseDto, error)
	// GetFaces implements getFaces operation.
	//
	// GET /faces
	GetFaces(ctx context.Context, params GetFacesParams) ([]AssetFaceResponseDto, error)
	// GetFileChecksums implements getFileChecksums operation.
	//
	// POST /reports/checksum
	GetFileChecksums(ctx context.Context, req *FileChecksumDto) ([]FileChecksumResponseDto, error)
	// GetFullSyncForUser implements getFullSyncForUser operation.
	//
	// POST /sync/full-sync
	GetFullSyncForUser(ctx context.Context, req *AssetFullSyncDto) ([]AssetResponseDto, error)
	// GetLibrary implements getLibrary operation.
	//
	// GET /libraries/{id}
	GetLibrary(ctx context.Context, params GetLibraryParams) (*LibraryResponseDto, error)
	// GetLibraryStatistics implements getLibraryStatistics operation.
	//
	// GET /libraries/{id}/statistics
	GetLibraryStatistics(ctx context.Context, params GetLibraryStatisticsParams) (*LibraryStatsResponseDto, error)
	// GetMapMarkers implements getMapMarkers operation.
	//
	// GET /map/markers
	GetMapMarkers(ctx context.Context, params GetMapMarkersParams) ([]MapMarkerResponseDto, error)
	// GetMemory implements getMemory operation.
	//
	// GET /memories/{id}
	GetMemory(ctx context.Context, params GetMemoryParams) (*MemoryResponseDto, error)
	// GetMemoryLane implements getMemoryLane operation.
	//
	// GET /assets/memory-lane
	GetMemoryLane(ctx context.Context, params GetMemoryLaneParams) ([]MemoryLaneResponseDto, error)
	// GetMyPreferences implements getMyPreferences operation.
	//
	// GET /users/me/preferences
	GetMyPreferences(ctx context.Context) (*UserPreferencesResponseDto, error)
	// GetMySharedLink implements getMySharedLink operation.
	//
	// GET /shared-links/me
	GetMySharedLink(ctx context.Context, params GetMySharedLinkParams) (*SharedLinkResponseDto, error)
	// GetMyUser implements getMyUser operation.
	//
	// GET /users/me
	GetMyUser(ctx context.Context) (*UserAdminResponseDto, error)
	// GetPartners implements getPartners operation.
	//
	// GET /partners
	GetPartners(ctx context.Context, params GetPartnersParams) ([]PartnerResponseDto, error)
	// GetPerson implements getPerson operation.
	//
	// GET /people/{id}
	GetPerson(ctx context.Context, params GetPersonParams) (*PersonResponseDto, error)
	// GetPersonStatistics implements getPersonStatistics operation.
	//
	// GET /people/{id}/statistics
	GetPersonStatistics(ctx context.Context, params GetPersonStatisticsParams) (*PersonStatisticsResponseDto, error)
	// GetPersonThumbnail implements getPersonThumbnail operation.
	//
	// GET /people/{id}/thumbnail
	GetPersonThumbnail(ctx context.Context, params GetPersonThumbnailParams) (GetPersonThumbnailOK, error)
	// GetProfileImage implements getProfileImage operation.
	//
	// GET /users/{id}/profile-image
	GetProfileImage(ctx context.Context, params GetProfileImageParams) (GetProfileImageOK, error)
	// GetRandom implements getRandom operation.
	//
	// This property was deprecated in v1.116.0.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /assets/random
	GetRandom(ctx context.Context, params GetRandomParams) ([]AssetResponseDto, error)
	// GetReverseGeocodingState implements getReverseGeocodingState operation.
	//
	// GET /system-metadata/reverse-geocoding-state
	GetReverseGeocodingState(ctx context.Context) (*ReverseGeocodingStateResponseDto, error)
	// GetSearchSuggestions implements getSearchSuggestions operation.
	//
	// GET /search/suggestions
	GetSearchSuggestions(ctx context.Context, params GetSearchSuggestionsParams) ([]string, error)
	// GetServerConfig implements getServerConfig operation.
	//
	// GET /server/config
	GetServerConfig(ctx context.Context) (*ServerConfigDto, error)
	// GetServerFeatures implements getServerFeatures operation.
	//
	// GET /server/features
	GetServerFeatures(ctx context.Context) (*ServerFeaturesDto, error)
	// GetServerLicense implements getServerLicense operation.
	//
	// GET /server/license
	GetServerLicense(ctx context.Context) (GetServerLicenseRes, error)
	// GetServerStatistics implements getServerStatistics operation.
	//
	// GET /server/statistics
	GetServerStatistics(ctx context.Context) (*ServerStatsResponseDto, error)
	// GetServerVersion implements getServerVersion operation.
	//
	// GET /server/version
	GetServerVersion(ctx context.Context) (*ServerVersionResponseDto, error)
	// GetSessions implements getSessions operation.
	//
	// GET /sessions
	GetSessions(ctx context.Context) ([]SessionResponseDto, error)
	// GetSharedLinkById implements getSharedLinkById operation.
	//
	// GET /shared-links/{id}
	GetSharedLinkById(ctx context.Context, params GetSharedLinkByIdParams) (*SharedLinkResponseDto, error)
	// GetStack implements getStack operation.
	//
	// GET /stacks/{id}
	GetStack(ctx context.Context, params GetStackParams) (*StackResponseDto, error)
	// GetStorage implements getStorage operation.
	//
	// GET /server/storage
	GetStorage(ctx context.Context) (*ServerStorageResponseDto, error)
	// GetStorageTemplateOptions implements getStorageTemplateOptions operation.
	//
	// GET /system-config/storage-template-options
	GetStorageTemplateOptions(ctx context.Context) (*SystemConfigTemplateStorageOptionDto, error)
	// GetSupportedMediaTypes implements getSupportedMediaTypes operation.
	//
	// GET /server/media-types
	GetSupportedMediaTypes(ctx context.Context) (*ServerMediaTypesResponseDto, error)
	// GetTagById implements getTagById operation.
	//
	// GET /tags/{id}
	GetTagById(ctx context.Context, params GetTagByIdParams) (*TagResponseDto, error)
	// GetTheme implements getTheme operation.
	//
	// GET /server/theme
	GetTheme(ctx context.Context) (*ServerThemeDto, error)
	// GetTimeBucket implements getTimeBucket operation.
	//
	// GET /timeline/bucket
	GetTimeBucket(ctx context.Context, params GetTimeBucketParams) ([]AssetResponseDto, error)
	// GetTimeBuckets implements getTimeBuckets operation.
	//
	// GET /timeline/buckets
	GetTimeBuckets(ctx context.Context, params GetTimeBucketsParams) ([]TimeBucketResponseDto, error)
	// GetUniqueOriginalPaths implements getUniqueOriginalPaths operation.
	//
	// GET /view/folder/unique-paths
	GetUniqueOriginalPaths(ctx context.Context) ([]string, error)
	// GetUser implements getUser operation.
	//
	// GET /users/{id}
	GetUser(ctx context.Context, params GetUserParams) (*UserResponseDto, error)
	// GetUserAdmin implements getUserAdmin operation.
	//
	// GET /admin/users/{id}
	GetUserAdmin(ctx context.Context, params GetUserAdminParams) (*UserAdminResponseDto, error)
	// GetUserLicense implements getUserLicense operation.
	//
	// GET /users/me/license
	GetUserLicense(ctx context.Context) (*LicenseResponseDto, error)
	// GetUserPreferencesAdmin implements getUserPreferencesAdmin operation.
	//
	// GET /admin/users/{id}/preferences
	GetUserPreferencesAdmin(ctx context.Context, params GetUserPreferencesAdminParams) (*UserPreferencesResponseDto, error)
	// GetVersionHistory implements getVersionHistory operation.
	//
	// GET /server/version-history
	GetVersionHistory(ctx context.Context) ([]ServerVersionHistoryResponseDto, error)
	// LinkOAuthAccount implements linkOAuthAccount operation.
	//
	// POST /oauth/link
	LinkOAuthAccount(ctx context.Context, req *OAuthCallbackDto) (*UserAdminResponseDto, error)
	// Login implements login operation.
	//
	// POST /auth/login
	Login(ctx context.Context, req *LoginCredentialDto) (*LoginResponseDto, error)
	// Logout implements logout operation.
	//
	// POST /auth/logout
	Logout(ctx context.Context) (*LogoutResponseDto, error)
	// MergePerson implements mergePerson operation.
	//
	// POST /people/{id}/merge
	MergePerson(ctx context.Context, req *MergePersonDto, params MergePersonParams) ([]BulkIdResponseDto, error)
	// PingServer implements pingServer operation.
	//
	// GET /server/ping
	PingServer(ctx context.Context) (*ServerPingResponse, error)
	// PlayAssetVideo implements playAssetVideo operation.
	//
	// GET /assets/{id}/video/playback
	PlayAssetVideo(ctx context.Context, params PlayAssetVideoParams) (PlayAssetVideoOK, error)
	// ReassignFaces implements reassignFaces operation.
	//
	// PUT /people/{id}/reassign
	ReassignFaces(ctx context.Context, req *AssetFaceUpdateDto, params ReassignFacesParams) ([]PersonResponseDto, error)
	// ReassignFacesById implements reassignFacesById operation.
	//
	// PUT /faces/{id}
	ReassignFacesById(ctx context.Context, req *FaceDto, params ReassignFacesByIdParams) (*PersonResponseDto, error)
	// RedirectOAuthToMobile implements redirectOAuthToMobile operation.
	//
	// GET /oauth/mobile-redirect
	RedirectOAuthToMobile(ctx context.Context) error
	// RemoveAssetFromAlbum implements removeAssetFromAlbum operation.
	//
	// DELETE /albums/{id}/assets
	RemoveAssetFromAlbum(ctx context.Context, req *BulkIdsDto, params RemoveAssetFromAlbumParams) ([]BulkIdResponseDto, error)
	// RemoveMemoryAssets implements removeMemoryAssets operation.
	//
	// DELETE /memories/{id}/assets
	RemoveMemoryAssets(ctx context.Context, req *BulkIdsDto, params RemoveMemoryAssetsParams) ([]BulkIdResponseDto, error)
	// RemovePartner implements removePartner operation.
	//
	// DELETE /partners/{id}
	RemovePartner(ctx context.Context, params RemovePartnerParams) error
	// RemoveSharedLink implements removeSharedLink operation.
	//
	// DELETE /shared-links/{id}
	RemoveSharedLink(ctx context.Context, params RemoveSharedLinkParams) error
	// RemoveSharedLinkAssets implements removeSharedLinkAssets operation.
	//
	// DELETE /shared-links/{id}/assets
	RemoveSharedLinkAssets(ctx context.Context, req *AssetIdsDto, params RemoveSharedLinkAssetsParams) ([]AssetIdsResponseDto, error)
	// RemoveUserFromAlbum implements removeUserFromAlbum operation.
	//
	// DELETE /albums/{id}/user/{userId}
	RemoveUserFromAlbum(ctx context.Context, params RemoveUserFromAlbumParams) error
	// ReplaceAsset implements replaceAsset operation.
	//
	// Replace the asset with new file, without changing its id.
	//
	// PUT /assets/{id}/original
	ReplaceAsset(ctx context.Context, req *AssetMediaReplaceDtoMultipart, params ReplaceAssetParams) (*AssetMediaResponseDto, error)
	// RestoreAssets implements restoreAssets operation.
	//
	// POST /trash/restore/assets
	RestoreAssets(ctx context.Context, req *BulkIdsDto) (*TrashResponseDto, error)
	// RestoreTrash implements restoreTrash operation.
	//
	// POST /trash/restore
	RestoreTrash(ctx context.Context) (*TrashResponseDto, error)
	// RestoreUserAdmin implements restoreUserAdmin operation.
	//
	// POST /admin/users/{id}/restore
	RestoreUserAdmin(ctx context.Context, params RestoreUserAdminParams) (*UserAdminResponseDto, error)
	// ReverseGeocode implements reverseGeocode operation.
	//
	// GET /map/reverse-geocode
	ReverseGeocode(ctx context.Context, params ReverseGeocodeParams) ([]MapReverseGeocodeResponseDto, error)
	// RunAssetJobs implements runAssetJobs operation.
	//
	// POST /assets/jobs
	RunAssetJobs(ctx context.Context, req *AssetJobsDto) error
	// ScanLibrary implements scanLibrary operation.
	//
	// POST /libraries/{id}/scan
	ScanLibrary(ctx context.Context, params ScanLibraryParams) error
	// SearchMemories implements searchMemories operation.
	//
	// GET /memories
	SearchMemories(ctx context.Context) ([]MemoryResponseDto, error)
	// SearchMetadata implements searchMetadata operation.
	//
	// POST /search/metadata
	SearchMetadata(ctx context.Context, req *MetadataSearchDto) (*SearchResponseDto, error)
	// SearchPerson implements searchPerson operation.
	//
	// GET /search/person
	SearchPerson(ctx context.Context, params SearchPersonParams) ([]PersonResponseDto, error)
	// SearchPlaces implements searchPlaces operation.
	//
	// GET /search/places
	SearchPlaces(ctx context.Context, params SearchPlacesParams) ([]PlacesResponseDto, error)
	// SearchRandom implements searchRandom operation.
	//
	// POST /search/random
	SearchRandom(ctx context.Context, req *RandomSearchDto) ([]AssetResponseDto, error)
	// SearchSmart implements searchSmart operation.
	//
	// POST /search/smart
	SearchSmart(ctx context.Context, req *SmartSearchDto) (*SearchResponseDto, error)
	// SearchStacks implements searchStacks operation.
	//
	// GET /stacks
	SearchStacks(ctx context.Context, params SearchStacksParams) ([]StackResponseDto, error)
	// SearchUsers implements searchUsers operation.
	//
	// GET /users
	SearchUsers(ctx context.Context) ([]UserResponseDto, error)
	// SearchUsersAdmin implements searchUsersAdmin operation.
	//
	// GET /admin/users
	SearchUsersAdmin(ctx context.Context, params SearchUsersAdminParams) ([]UserAdminResponseDto, error)
	// SendJobCommand implements sendJobCommand operation.
	//
	// PUT /jobs/{id}
	SendJobCommand(ctx context.Context, req *JobCommandDto, params SendJobCommandParams) (*JobStatusDto, error)
	// SendTestEmail implements sendTestEmail operation.
	//
	// POST /notifications/test-email
	SendTestEmail(ctx context.Context, req *SystemConfigSmtpDto) (*TestEmailResponseDto, error)
	// SetServerLicense implements setServerLicense operation.
	//
	// PUT /server/license
	SetServerLicense(ctx context.Context, req *LicenseKeyDto) (*LicenseResponseDto, error)
	// SetUserLicense implements setUserLicense operation.
	//
	// PUT /users/me/license
	SetUserLicense(ctx context.Context, req *LicenseKeyDto) (*LicenseResponseDto, error)
	// SignUpAdmin implements signUpAdmin operation.
	//
	// POST /auth/admin-sign-up
	SignUpAdmin(ctx context.Context, req *SignUpDto) (*UserAdminResponseDto, error)
	// StartOAuth implements startOAuth operation.
	//
	// POST /oauth/authorize
	StartOAuth(ctx context.Context, req *OAuthConfigDto) (*OAuthAuthorizeResponseDto, error)
	// TagAssets implements tagAssets operation.
	//
	// PUT /tags/{id}/assets
	TagAssets(ctx context.Context, req *BulkIdsDto, params TagAssetsParams) ([]BulkIdResponseDto, error)
	// UnlinkOAuthAccount implements unlinkOAuthAccount operation.
	//
	// POST /oauth/unlink
	UnlinkOAuthAccount(ctx context.Context) (*UserAdminResponseDto, error)
	// UntagAssets implements untagAssets operation.
	//
	// DELETE /tags/{id}/assets
	UntagAssets(ctx context.Context, req *BulkIdsDto, params UntagAssetsParams) ([]BulkIdResponseDto, error)
	// UpdateAdminOnboarding implements updateAdminOnboarding operation.
	//
	// POST /system-metadata/admin-onboarding
	UpdateAdminOnboarding(ctx context.Context, req *AdminOnboardingUpdateDto) error
	// UpdateAlbumInfo implements updateAlbumInfo operation.
	//
	// PATCH /albums/{id}
	UpdateAlbumInfo(ctx context.Context, req *UpdateAlbumDto, params UpdateAlbumInfoParams) (*AlbumResponseDto, error)
	// UpdateAlbumUser implements updateAlbumUser operation.
	//
	// PUT /albums/{id}/user/{userId}
	UpdateAlbumUser(ctx context.Context, req *UpdateAlbumUserDto, params UpdateAlbumUserParams) error
	// UpdateApiKey implements updateApiKey operation.
	//
	// PUT /api-keys/{id}
	UpdateApiKey(ctx context.Context, req *APIKeyUpdateDto, params UpdateApiKeyParams) (*APIKeyResponseDto, error)
	// UpdateAsset implements updateAsset operation.
	//
	// PUT /assets/{id}
	UpdateAsset(ctx context.Context, req *UpdateAssetDto, params UpdateAssetParams) (*AssetResponseDto, error)
	// UpdateAssets implements updateAssets operation.
	//
	// PUT /assets
	UpdateAssets(ctx context.Context, req *AssetBulkUpdateDto) error
	// UpdateConfig implements updateConfig operation.
	//
	// PUT /system-config
	UpdateConfig(ctx context.Context, req *SystemConfigDto) (*SystemConfigDto, error)
	// UpdateLibrary implements updateLibrary operation.
	//
	// PUT /libraries/{id}
	UpdateLibrary(ctx context.Context, req *UpdateLibraryDto, params UpdateLibraryParams) (*LibraryResponseDto, error)
	// UpdateMemory implements updateMemory operation.
	//
	// PUT /memories/{id}
	UpdateMemory(ctx context.Context, req *MemoryUpdateDto, params UpdateMemoryParams) (*MemoryResponseDto, error)
	// UpdateMyPreferences implements updateMyPreferences operation.
	//
	// PUT /users/me/preferences
	UpdateMyPreferences(ctx context.Context, req *UserPreferencesUpdateDto) (*UserPreferencesResponseDto, error)
	// UpdateMyUser implements updateMyUser operation.
	//
	// PUT /users/me
	UpdateMyUser(ctx context.Context, req *UserUpdateMeDto) (*UserAdminResponseDto, error)
	// UpdatePartner implements updatePartner operation.
	//
	// PUT /partners/{id}
	UpdatePartner(ctx context.Context, req *UpdatePartnerDto, params UpdatePartnerParams) (*PartnerResponseDto, error)
	// UpdatePeople implements updatePeople operation.
	//
	// PUT /people
	UpdatePeople(ctx context.Context, req *PeopleUpdateDto) ([]BulkIdResponseDto, error)
	// UpdatePerson implements updatePerson operation.
	//
	// PUT /people/{id}
	UpdatePerson(ctx context.Context, req *PersonUpdateDto, params UpdatePersonParams) (*PersonResponseDto, error)
	// UpdateSharedLink implements updateSharedLink operation.
	//
	// PATCH /shared-links/{id}
	UpdateSharedLink(ctx context.Context, req *SharedLinkEditDto, params UpdateSharedLinkParams) (*SharedLinkResponseDto, error)
	// UpdateStack implements updateStack operation.
	//
	// PUT /stacks/{id}
	UpdateStack(ctx context.Context, req *StackUpdateDto, params UpdateStackParams) (*StackResponseDto, error)
	// UpdateTag implements updateTag operation.
	//
	// PUT /tags/{id}
	UpdateTag(ctx context.Context, req *TagUpdateDto, params UpdateTagParams) (*TagResponseDto, error)
	// UpdateUserAdmin implements updateUserAdmin operation.
	//
	// PUT /admin/users/{id}
	UpdateUserAdmin(ctx context.Context, req *UserAdminUpdateDto, params UpdateUserAdminParams) (*UserAdminResponseDto, error)
	// UpdateUserPreferencesAdmin implements updateUserPreferencesAdmin operation.
	//
	// PUT /admin/users/{id}/preferences
	UpdateUserPreferencesAdmin(ctx context.Context, req *UserPreferencesUpdateDto, params UpdateUserPreferencesAdminParams) (*UserPreferencesResponseDto, error)
	// UploadAsset implements uploadAsset operation.
	//
	// POST /assets
	UploadAsset(ctx context.Context, req *AssetMediaCreateDtoMultipart, params UploadAssetParams) (*AssetMediaResponseDtoStatusCode, error)
	// UpsertTags implements upsertTags operation.
	//
	// PUT /tags
	UpsertTags(ctx context.Context, req *TagUpsertDto) ([]TagResponseDto, error)
	// Validate implements validate operation.
	//
	// POST /libraries/{id}/validate
	Validate(ctx context.Context, req *ValidateLibraryDto, params ValidateParams) (*ValidateLibraryResponseDto, error)
	// ValidateAccessToken implements validateAccessToken operation.
	//
	// POST /auth/validateToken
	ValidateAccessToken(ctx context.Context) (*ValidateAccessTokenResponseDto, error)
	// ViewAsset implements viewAsset operation.
	//
	// GET /assets/{id}/thumbnail
	ViewAsset(ctx context.Context, params ViewAssetParams) (ViewAssetOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
