on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
      - run: go generate ./...
      - run: go build .
      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: immich-sync